# This workflow is for tests that require a single cluster.
name: Run e2e tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'CHANGELOG/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'CHANGELOG/**'
jobs:
  kind_e2e_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        e2e_test:
          - CreateSingleDatacenterCluster
          - CreateStargateAndDatacenter
          - CreateSingleReaper
          - CreateReaperAndDatacenter
          - CreateSingleMedusa
          - ConfigControllerRestarts
        makefile_setup_target: [e2e-setup-single]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get PR head sha
        run: |
          if [[ '${{ inputs.event_name }}' == 'pull_request' ]]; then
            echo ::set-output name=sha::${{ github.event.pull_request.head.sha }}
          else
            echo ::set-output name=sha::${{ github.sha }}
          fi
      - uses: .github/workflows/kind_e2e_test_execution.yaml
        with:
          e2e_test: ${{ matrix.e2e_test }}
          makefile_setup_target: ${{ matrix.makefile_setup_target }}
          github_sha: ${{ env.sha }}
          github_head_ref: ${{ github.head_ref }}
          event_name: ${{ github.event_name }}
    
