# This workflow is for tests that require a single cluster.
name: Run e2e tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'CHANGELOG/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'CHANGELOG/**'
jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image_var.outputs.image }}
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request'
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-integ-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-integ-
      - name: Set build tags
        id: set_build_tags
        run: |
          image="k8ssandra/k8ssandra-operator:latest"
          echo "build_tags=$image" >> $GITHUB_ENV
          echo "image=$image" >> $GITHUB_ENV
      - name: Update build tags
        id: update_build_tags
        if: startsWith(github.head_ref, 'prepare-release-')
        run: |
          branch_name=${{ github.head_ref }}
          release_tag=k8ssandra/k8ssandra-operator:${branch_name:16}
          echo "image=$release_tag" >> $GITHUB_ENV
          echo "build_tags=k8ssandra/k8ssandra-operator:latest,$release_tag" >> $GITHUB_ENV
      - name: Set immage output var
        id: set_image_var
        run: echo ::set-output name=image::${{ env.image }}
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: false
          tags: ${{ env.build_tags }}
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/k8ssandra-operator.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Upload k8ssandra-operator image
        uses: actions/upload-artifact@v2
        with:
          name: k8ssandra-operator
          path: /tmp/k8ssandra-operator.tar
  kind_e2e_tests:
    runs-on: ubuntu-latest
    needs: build_image
    strategy:
      matrix:
        e2e_test:
          - CreateSingleDatacenterCluster
          - CreateStargateAndDatacenter
          - CreateSingleReaper
          - CreateReaperAndDatacenter
          - CreateSingleMedusa
          - ConfigControllerRestarts
        makefile_setup_target: [e2e-setup-single]
      fail-fast: false
    name: ${{ matrix.e2e_test }}
    uses: .github/workflows/kind_e2e_test_execution.yaml
    with:
      e2e_test: ${{ matrix.e2e_test }}
      makefile_setup_target: ${{ matrix.makefile_setup_target }}
    
